name: CI/CD

on:
  push:
    branches: [ "publish-fe", "publish-be", "publish-all" ]
    paths: ['.github/workflows/**', 'Projects/**']
  workflow_dispatch:

jobs:
  build-and-deploy-fe:
    if: |
      github.event_name == 'push' && (github.ref == 'refs/heads/publish-fe' || github.ref == 'refs/heads/publish-all') || 
      github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./Projects/fe
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Projects/fe/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
